<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) 
        				->prependStylesheet($this->basePath('jqwidgets/styles/jqx.base.css')) 
        				->prependStylesheet($this->basePath('jqwidgets/styles/jqx.black.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        	//->prependFile($this->basepath('js/require.js', 'text/javascript', array('data-main' => 'js/main')))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
		<script type="text/javascript" data-main="js/main" src="js/require.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
        
        <div id='jqxTree' style="width:300px;hieght:300px">
	        <ul>
	            <li item-selected='true'>Home</li>
	            <li item-expanded='true'>Solutions
	                <ul>
	                    <li>Education</li>
	                    <li>Financial services</li>
	                    <li>Government</li>
	                    <li>Manufacturing</li>
	                    <li>Solutions
	                        <ul>
	                            <li>Consumer photo and video</li>
	                            <li>Mobile</li>
	                            <li>Rich Internet applications</li>
	                            <li>Technical communication</li>
	                            <li>Training and eLearning</li>
	                            <li>Web conferencing</li>
	                        </ul>
	                    </li>
	                    <li>All industries and solutions</li>
	                </ul>
	            </li>
	        </ul>
	    </div>
        
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
